require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbbrvsController do

  # This should return the minimal set of attributes required to create a valid
  # Abbrv. As you add validations to Abbrv, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Abrv" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbbrvsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all abbrvs as @abbrvs" do
      abbrv = Abbrv.create! valid_attributes
      get :index, {}, valid_session
      assigns(:abbrvs).should eq([abbrv])
    end
  end

  describe "GET show" do
    it "assigns the requested abbrv as @abbrv" do
      abbrv = Abbrv.create! valid_attributes
      get :show, {:id => abbrv.to_param}, valid_session
      assigns(:abbrv).should eq(abbrv)
    end
  end

  describe "GET new" do
    it "assigns a new abbrv as @abbrv" do
      get :new, {}, valid_session
      assigns(:abbrv).should be_a_new(Abbrv)
    end
  end

  describe "GET edit" do
    it "assigns the requested abbrv as @abbrv" do
      abbrv = Abbrv.create! valid_attributes
      get :edit, {:id => abbrv.to_param}, valid_session
      assigns(:abbrv).should eq(abbrv)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Abbrv" do
        expect {
          post :create, {:abbrv => valid_attributes}, valid_session
        }.to change(Abbrv, :count).by(1)
      end

      it "assigns a newly created abbrv as @abbrv" do
        post :create, {:abbrv => valid_attributes}, valid_session
        assigns(:abbrv).should be_a(Abbrv)
        assigns(:abbrv).should be_persisted
      end

      it "redirects to the created abbrv" do
        post :create, {:abbrv => valid_attributes}, valid_session
        response.should redirect_to(Abbrv.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved abbrv as @abbrv" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abbrv.any_instance.stub(:save).and_return(false)
        post :create, {:abbrv => { "Abrv" => "invalid value" }}, valid_session
        assigns(:abbrv).should be_a_new(Abbrv)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Abbrv.any_instance.stub(:save).and_return(false)
        post :create, {:abbrv => { "Abrv" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested abbrv" do
        abbrv = Abbrv.create! valid_attributes
        # Assuming there are no other abbrvs in the database, this
        # specifies that the Abbrv created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Abbrv.any_instance.should_receive(:update).with({ "Abrv" => "MyString" })
        put :update, {:id => abbrv.to_param, :abbrv => { "Abrv" => "MyString" }}, valid_session
      end

      it "assigns the requested abbrv as @abbrv" do
        abbrv = Abbrv.create! valid_attributes
        put :update, {:id => abbrv.to_param, :abbrv => valid_attributes}, valid_session
        assigns(:abbrv).should eq(abbrv)
      end

      it "redirects to the abbrv" do
        abbrv = Abbrv.create! valid_attributes
        put :update, {:id => abbrv.to_param, :abbrv => valid_attributes}, valid_session
        response.should redirect_to(abbrv)
      end
    end

    describe "with invalid params" do
      it "assigns the abbrv as @abbrv" do
        abbrv = Abbrv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abbrv.any_instance.stub(:save).and_return(false)
        put :update, {:id => abbrv.to_param, :abbrv => { "Abrv" => "invalid value" }}, valid_session
        assigns(:abbrv).should eq(abbrv)
      end

      it "re-renders the 'edit' template" do
        abbrv = Abbrv.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Abbrv.any_instance.stub(:save).and_return(false)
        put :update, {:id => abbrv.to_param, :abbrv => { "Abrv" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested abbrv" do
      abbrv = Abbrv.create! valid_attributes
      expect {
        delete :destroy, {:id => abbrv.to_param}, valid_session
      }.to change(Abbrv, :count).by(-1)
    end

    it "redirects to the abbrvs list" do
      abbrv = Abbrv.create! valid_attributes
      delete :destroy, {:id => abbrv.to_param}, valid_session
      response.should redirect_to(abbrvs_url)
    end
  end

end
