require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FteamsController do

  # This should return the minimal set of attributes required to create a valid
  # Fteam. As you add validations to Fteam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Team" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FteamsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fteams as @fteams" do
      fteam = Fteam.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fteams).should eq([fteam])
    end
  end

  describe "GET show" do
    it "assigns the requested fteam as @fteam" do
      fteam = Fteam.create! valid_attributes
      get :show, {:id => fteam.to_param}, valid_session
      assigns(:fteam).should eq(fteam)
    end
  end

  describe "GET new" do
    it "assigns a new fteam as @fteam" do
      get :new, {}, valid_session
      assigns(:fteam).should be_a_new(Fteam)
    end
  end

  describe "GET edit" do
    it "assigns the requested fteam as @fteam" do
      fteam = Fteam.create! valid_attributes
      get :edit, {:id => fteam.to_param}, valid_session
      assigns(:fteam).should eq(fteam)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fteam" do
        expect {
          post :create, {:fteam => valid_attributes}, valid_session
        }.to change(Fteam, :count).by(1)
      end

      it "assigns a newly created fteam as @fteam" do
        post :create, {:fteam => valid_attributes}, valid_session
        assigns(:fteam).should be_a(Fteam)
        assigns(:fteam).should be_persisted
      end

      it "redirects to the created fteam" do
        post :create, {:fteam => valid_attributes}, valid_session
        response.should redirect_to(Fteam.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fteam as @fteam" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fteam.any_instance.stub(:save).and_return(false)
        post :create, {:fteam => { "Team" => "invalid value" }}, valid_session
        assigns(:fteam).should be_a_new(Fteam)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fteam.any_instance.stub(:save).and_return(false)
        post :create, {:fteam => { "Team" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fteam" do
        fteam = Fteam.create! valid_attributes
        # Assuming there are no other fteams in the database, this
        # specifies that the Fteam created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fteam.any_instance.should_receive(:update).with({ "Team" => "MyString" })
        put :update, {:id => fteam.to_param, :fteam => { "Team" => "MyString" }}, valid_session
      end

      it "assigns the requested fteam as @fteam" do
        fteam = Fteam.create! valid_attributes
        put :update, {:id => fteam.to_param, :fteam => valid_attributes}, valid_session
        assigns(:fteam).should eq(fteam)
      end

      it "redirects to the fteam" do
        fteam = Fteam.create! valid_attributes
        put :update, {:id => fteam.to_param, :fteam => valid_attributes}, valid_session
        response.should redirect_to(fteam)
      end
    end

    describe "with invalid params" do
      it "assigns the fteam as @fteam" do
        fteam = Fteam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fteam.any_instance.stub(:save).and_return(false)
        put :update, {:id => fteam.to_param, :fteam => { "Team" => "invalid value" }}, valid_session
        assigns(:fteam).should eq(fteam)
      end

      it "re-renders the 'edit' template" do
        fteam = Fteam.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fteam.any_instance.stub(:save).and_return(false)
        put :update, {:id => fteam.to_param, :fteam => { "Team" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fteam" do
      fteam = Fteam.create! valid_attributes
      expect {
        delete :destroy, {:id => fteam.to_param}, valid_session
      }.to change(Fteam, :count).by(-1)
    end

    it "redirects to the fteams list" do
      fteam = Fteam.create! valid_attributes
      delete :destroy, {:id => fteam.to_param}, valid_session
      response.should redirect_to(fteams_url)
    end
  end

end
