require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LivePlayersController do

  # This should return the minimal set of attributes required to create a valid
  # LivePlayer. As you add validations to LivePlayer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "Nid" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LivePlayersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all live_players as @live_players" do
      live_player = LivePlayer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:live_players).should eq([live_player])
    end
  end

  describe "GET show" do
    it "assigns the requested live_player as @live_player" do
      live_player = LivePlayer.create! valid_attributes
      get :show, {:id => live_player.to_param}, valid_session
      assigns(:live_player).should eq(live_player)
    end
  end

  describe "GET new" do
    it "assigns a new live_player as @live_player" do
      get :new, {}, valid_session
      assigns(:live_player).should be_a_new(LivePlayer)
    end
  end

  describe "GET edit" do
    it "assigns the requested live_player as @live_player" do
      live_player = LivePlayer.create! valid_attributes
      get :edit, {:id => live_player.to_param}, valid_session
      assigns(:live_player).should eq(live_player)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LivePlayer" do
        expect {
          post :create, {:live_player => valid_attributes}, valid_session
        }.to change(LivePlayer, :count).by(1)
      end

      it "assigns a newly created live_player as @live_player" do
        post :create, {:live_player => valid_attributes}, valid_session
        assigns(:live_player).should be_a(LivePlayer)
        assigns(:live_player).should be_persisted
      end

      it "redirects to the created live_player" do
        post :create, {:live_player => valid_attributes}, valid_session
        response.should redirect_to(LivePlayer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved live_player as @live_player" do
        # Trigger the behavior that occurs when invalid params are submitted
        LivePlayer.any_instance.stub(:save).and_return(false)
        post :create, {:live_player => { "Nid" => "invalid value" }}, valid_session
        assigns(:live_player).should be_a_new(LivePlayer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LivePlayer.any_instance.stub(:save).and_return(false)
        post :create, {:live_player => { "Nid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested live_player" do
        live_player = LivePlayer.create! valid_attributes
        # Assuming there are no other live_players in the database, this
        # specifies that the LivePlayer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LivePlayer.any_instance.should_receive(:update).with({ "Nid" => "1" })
        put :update, {:id => live_player.to_param, :live_player => { "Nid" => "1" }}, valid_session
      end

      it "assigns the requested live_player as @live_player" do
        live_player = LivePlayer.create! valid_attributes
        put :update, {:id => live_player.to_param, :live_player => valid_attributes}, valid_session
        assigns(:live_player).should eq(live_player)
      end

      it "redirects to the live_player" do
        live_player = LivePlayer.create! valid_attributes
        put :update, {:id => live_player.to_param, :live_player => valid_attributes}, valid_session
        response.should redirect_to(live_player)
      end
    end

    describe "with invalid params" do
      it "assigns the live_player as @live_player" do
        live_player = LivePlayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LivePlayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => live_player.to_param, :live_player => { "Nid" => "invalid value" }}, valid_session
        assigns(:live_player).should eq(live_player)
      end

      it "re-renders the 'edit' template" do
        live_player = LivePlayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LivePlayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => live_player.to_param, :live_player => { "Nid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested live_player" do
      live_player = LivePlayer.create! valid_attributes
      expect {
        delete :destroy, {:id => live_player.to_param}, valid_session
      }.to change(LivePlayer, :count).by(-1)
    end

    it "redirects to the live_players list" do
      live_player = LivePlayer.create! valid_attributes
      delete :destroy, {:id => live_player.to_param}, valid_session
      response.should redirect_to(live_players_url)
    end
  end

end
